language: generic

sudo: false

env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
  matrix:
    - EMACS_VERSION=25.1
    - EMACS_VERSION=25.2
    - EMACS_VERSION=master
  allow_failures:
    - env: EMACS_VERSION=master

install:
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - $EMACS --version

script:
  - cd
  - mv "$TRAVIS_BUILD_DIR" ~/.emacs.d
  - cd ~/.emacs.d
  - $EMACS --batch -l init.el -f batch-byte-compile init.el

notifications:
  email:
    on_failure: never
